// 🗂 Diccionario con traducciones personalizadas
const traducciones = {
  amarillo: {
    en: "yellow",
    panix: "kwtsi",
    sanjuan: "ntsic",
    yolo: "Kutsy",
    yaite: "ntsi",
  },
  azul: {
    en: "blue",
    panix: "bshe",
    sanjuan: "shig",
    yolo: "kwishi’",
    yaite: "fshe",
  },
  azul_marino: {
    en: "navy blue",
    panix: "bshe ngtoa",
    sanjuan: "shig ntaf",
    yolo: "kwishi’ ngata",
    yaite: "fshe mta",
  },
  blanco: {
    en: "white",
    panix: "ngtean",
    sanjuan: "ntenf",
    yolo: "Ngatë",
    yaite: "mte",
  },
  café: {
    en: "brown",
    panix: "ka jwea",
    sanjuan: "kaajwea",
    yolo: "Kafee",
    yaite: "cafee",
  },
  crema: {
    en: "cream",
    panix: "ktse",
    sanjuan: "ntenf ntsic",
    yolo: "traducción no disponible",
    yaite: "traduccion no disponible",
  },
  dorado: {
    en: "gold",
    panix: "ktse shoa",
    sanjuan: "ntsic shaa",
    yolo: "Katsi",
    yaite: "ndui",
  },
  gris: {
    en: "gray",
    panix: "yu",
    sanjuan: "jig",
    yolo: "Gii",
    yaite: "ji",
  },
  morado: {
    en: "purple",
    panix: "kwoa",
    sanjuan: "kwaf",
    yolo: "Kwa",
    yaite: "kua",
  },
  naranja: {
    en: "orange",
    panix: "yea",
    sanjuan: "ntsic yeb",
    yolo: "Yee",
    yaite: "misha",
  },
  negro: {
    en: "black",
    panix: "ngtoa",
    sanjuan: "ntaf",
    yolo: "Ngata",
    yaite: "mto",
  },
  rojo: {
    en: "red",
    panix: "ngoa oa",
    sanjuan: "ngqae",
    yolo: "nga’a",
    yaite: "naa",
  },
  verde: {
    en: "green",
    panix: "ngoa oa ika",
    sanjuan: "ngqag",
    yolo: "nga’a",
    yaite: "nia",
  },
  rosa: {
    en: "pink",
    panix: "shwiyoa",
    sanjuan: "ngqae jneqe",
    yolo: "nga’aa kwine’",
    yaite: "naamne",
  },
  abeja: {
    en: "bee",
    panix: "kwton",
    sanjuan: "kwaaton",
    yolo: "kwitü",
    yaite: "ftu",
  },
  alacran: {
    en: "scorpion",
    panix: "seen",
    sanjuan: "seeng",
    yolo: "sne’ë",
    yaite: "see",
  },
  arana: {
    en: "spider",
    panix: "ngwiyu",
    sanjuan: "ngwiyug",
    yolo: "ngwiyu’",
    yaite: "mbiu",
  },
  armadillo: {
    en: "armadillo",
    panix: "kwiin",
    sanjuan: "kwin",
    yolo: "gukwï",
    yaite: "kuif",
  },
  becerro: {
    en: "calf",
    panix: "shke ro",
    sanjuan: "shkerog",
    yolo: "buta kwine’",
    yaite: "fta",
  },
  borrego: {
    en: "sheep",
    panix: "slya",
    sanjuan: "slya",
    yolo: "silyia’",
    yaite: "slia",
  },
  buho: {
    en: "owl",
    panix: "jonskan",
    sanjuan: "junskan",
    yolo: "Kojo",
    yaite: "juu",
  },
  caballo: {
    en: "horse",
    panix: "byo",
    sanjuan: "byog",
    yolo: "kwiyu",
    yaite: "fiu",
  },
  camaron: {
    en: "shrimp",
    panix: "taa",
    sanjuan: "taag",
    yolo: "tit’ta",
    yaite: "ta",
  },
  cangrejo: {
    en: "crab",
    panix: "kwe",
    sanjuan: "kweg",
    yolo: "kwe",
    yaite: "ke",
  },
  caracol: {
    en: "snail",
    panix: "nee",
    sanjuan: "neeg",
    yolo: "minee",
    yaite: "mne",
  },
  cerdo: {
    en: "pig",
    panix: "kwea",
    sanjuan: "kwyaa",
    yolo: "kuwe",
    yaite: "kuel",
  },
  chapulin: {
    en: "grasshopper",
    panix: "sku",
    sanjuan: "skug",
    yolo: "traducción no disponible",
    yaite: "sku",
  },
  colibri: {
    en: "hummingbird",
    panix: "biyu",
    sanjuan: "biyug",
    yolo: "tsu’ku",
    yaite: "jiu",
  },
  conejo: {
    en: "rabbit",
    panix: "chakwichi",
    sanjuan: "chakwichig",
    yolo: "glyee",
    yaite: "kakti",
  },
  coyote: {
    en: "coyote",
    panix: "ngwoo",
    sanjuan: "ngwoog",
    yolo: "kwichi",
    yaite: "oo",
  },
  gallina: {
    en: "hen",
    panix: "kwtu sho",
    sanjuan: "kwtu shog",
    yolo: "tuwa",
    yaite: "ftu",
  },
  gallo: {
    en: "rooster",
    panix: "kwe",
    sanjuan: "kweg",
    yolo: "kwi’ta’",
    yaite: "lafe",
  },
  gato: {
    en: "cat",
    panix: "shtyoan",
    sanjuan: "shtyoang",
    yolo: "sukwa’",
    yaite: "stñu",
  },
  guajolote: {
    en: "turkey",
    panix: "kwisu",
    sanjuan: "kwisug",
    yolo: "kwityä",
    yaite: "latshot",
  },
  iguana: {
    en: "iguana",
    panix: "kutsi",
    sanjuan: "kutsig",
    yolo: "Kwinä",
    yaite: "ftsi",
  },
  leon: {
    en: "lion",
    panix: "kwichi",
    sanjuan: "kwichig",
    yolo: "kute’",
    yaite: "fkhi",
  },
  lobo: {
    en: "wolf",
    panix: "kwaa",
    sanjuan: "kwaag",
    yolo: "che’e",
    yaite: "snio",
  },
  mariposa: {
    en: "butterfly",
    panix: "si",
    sanjuan: "sig",
    yolo: "bichi",
    yaite: "si",
  },
  mosquito: {
    en: "mosquito",
    panix: "kwiya",
    sanjuan: "kwiyag",
    yolo: "gushe’ë",
    yaite: "fia",
  },
  perro: {
    en: "dog",
    panix: "shne",
    sanjuan: "shneg",
    yolo: "kwisu’",
    yaite: "sne",
  },
  pez: {
    en: "fish",
    panix: "kula",
    sanjuan: "kulag",
    yolo: "kunu’",
    yaite: "fla",
  },
  rana: {
    en: "frog",
    panix: "kwtyi",
    sanjuan: "kwtyig",
    yolo: "kutsy",
    yaite: "fty",
  },
  tigre: {
    en: "tiger",
    panix: "kwichi",
    sanjuan: "kwichig",
    yolo: "kutsy yü",
    yaite: "fchi",
  },
  tortuga: {
    en: "turtle",
    panix: "kuun",
    sanjuan: "kuung",
    yolo: "kwichi katsi",
    yaite: "ksii",
  },
  vaca: {
    en: "cow",
    panix: "kuta",
    sanjuan: "kutag",
    yolo: "Lobo",
    yaite: "fto",
  },
  venado: {
    en: "deer",
    panix: "kwnya",
    sanjuan: "kwnyag",
    yolo: "kshee",
    yaite: "fño",
  },
  zorro: {
    en: "fox",
    panix: "kutaa",
    sanjuan: "kutaag",
    yolo: "lasy",
    yaite: "fta",
  },
  lunes: {
    en: "monday",
    panix: "luni",
    sanjuan: "tsan ne",
    yolo: "",
    yaite: "luni",
  },
  martes: {
    en: "tuesday",
    panix: "marte",
    sanjuan: "tsan nte",
    yolo: "",
    yaite: "marte",
  },
  miercoles: {
    en: "wednesday",
    panix: "merku",
    sanjuan: "tsan nku",
    yolo: "",
    yaite: "mirku",
  },
  jueves: {
    en: "thursday",
    panix: "jwebe",
    sanjuan: "tsan jwebe",
    yolo: "",
    yaite: "jueve",
  },
  viernes: {
    en: "friday",
    panix: "biyerne",
    sanjuan: "tsan mbyerne",
    yolo: "",
    yaite: "vierni",
  },
  sabado: {
    en: "saturday",
    panix: "saro",
    sanjuan: "tsan saru",
    yolo: "",
    yaite: "sadu",
  },
  domingo: {
    en: "sunday",
    panix: "teminku",
    sanjuan: "tsan timinku",
    yolo: "",
    yaite: "timiniku",
  },
  hoy: {
    en: "today",
    panix: "tsan ni",
    sanjuan: "nyic",
    yolo: "",
    yaite: "ni",
  },
  manana: {
    en: "tomorrow",
    panix: "kyaa",
    sanjuan: "kyaf",
    yolo: "",
    yaite: "kia",
  },
  ayer: {
    en: "yesterday",
    panix: "kaa",
    sanjuan: "kaf",
    yolo: "",
    yaite: "ka",
  },
  anteayer: {
    en: "day before yesterday",
    panix: "ti",
    sanjuan: "kaf ti",
    yolo: "",
    yaite: "ti",
  },
  pasado_manana: {
    en: "day after tomorrow",
    panix: "wcha",
    sanjuan: "kchaa",
    yolo: "",
    yaite: "fcha",
  },
  boca: {
    en: "mouth",
    panix: "tuwa",
    sanjuan: "ysuc",
    yolo: "",
    yaite: "ua",
  },
  brazo: {
    en: "arm",
    panix: "li skun",
    sanjuan: "shwag",
    yolo: "",
    yaite: "sknu",
  },
  cabello: {
    en: "hair",
    panix: "kichan ke",
    sanjuan: "ndyaqc",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  cabeza: {
    en: "head",
    panix: "ke",
    sanjuan: "yjog",
    yolo: "",
    yaite: "ke",
  },
  ceja: {
    en: "eyebrow",
    panix: "kichan ykaan",
    sanjuan: "jyaa",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  cintura: {
    en: "waist",
    panix: "sii",
    sanjuan: "nda ji",
    yolo: "",
    yaite: "sii",
  },
  codo: {
    en: "elbow",
    panix: "sku",
    sanjuan: "skwaa",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  corazon: {
    en: "heart",
    panix: "kasiya",
    sanjuan: "jnyaqf",
    yolo: "",
    yaite: "tsia",
  },
  cuello: {
    en: "neck",
    panix: "ynin ynen",
    sanjuan: "stena",
    yolo: "",
    yaite: "kaini",
  },
  dedo: {
    en: "finger",
    panix: "shñin",
    sanjuan: "ngane",
    yolo: "",
    yaite: "loya",
  },
  diente: {
    en: "tooth",
    panix: "liya",
    sanjuan: "luqh",
    yolo: "",
    yaite: "lia",
  },
  espalda: {
    en: "back",
    panix: "chun",
    sanjuan: "ndlabb",
    yolo: "",
    yaite: "khuu",
  },
  estomago: {
    en: "stomach",
    panix: "ne",
    sanjuan: "ntqana",
    yolo: "",
    yaite: "lotie",
  },
  frente: {
    en: "forehead",
    panix: "twoa tykan",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "iko",
  },
  gluteo: {
    en: "buttock",
    panix: "kuna suun",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "fnotsue",
  },
  hombro: {
    en: "shoulder",
    panix: "skun",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "mblusku",
  },
  labio: {
    en: "lip",
    panix: "kijin tuwa",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "jiu’a",
  },
  lengua: {
    en: "tongue",
    panix: "itse",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "tshe",
  },
  mano: {
    en: "hand",
    panix: "ya",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "jia",
  },
  mejilla: {
    en: "cheek",
    panix: "ska",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "skoo",
  },
  muneca: {
    en: "wrist",
    panix: "ynin ya",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "nio ya",
  },
  muslo: {
    en: "thigh",
    panix: "ndan",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "fnu da",
  },
  nariz: {
    en: "nose",
    panix: "siyen",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "sie",
  },
  oido: {
    en: "ear (inner)",
    panix: "tunskan",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "tio tusku",
  },
  ojo: {
    en: "eye",
    panix: "kuloo",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "llou",
  },
  ombligo: {
    en: "belly button",
    panix: "tyu",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "tiu",
  },
  oreja: {
    en: "ear (outer)",
    panix: "jin nxkan",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  pantorrilla: {
    en: "calf",
    panix: "kuna keityi kiya",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  parpado: {
    en: "eyelid",
    panix: "kijin kiloo",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "ji kloo",
  },
  pecho: {
    en: "chest",
    panix: "tiye",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  pestana: {
    en: "eyelash",
    panix: "kichan kiloo",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "kho klo",
  },
  pie: {
    en: "foot",
    panix: "kiya",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "kia",
  },
  pulmon: {
    en: "lung",
    panix: "tsin",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "luu",
  },
  rodilla: {
    en: "knee",
    panix: "xtyin",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "kesh tky",
  },
  rotula: {
    en: "kneecap",
    panix: "ke xtyin",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  talon: {
    en: "heel",
    panix: "suwe kiya",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  tobillo: {
    en: "ankle",
    panix: "ynin kiya",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  una: {
    en: "nail",
    panix: "stan",
    sanjuan: "traduccion no disponible",
    yolo: "",
    yaite: "sto",
  },
  aguacate: {
    en: "avocado",
    panix: "kan",
    sanjuan: "kan",
    yolo: "",
    yaite: "kan",
  },
  ajo: {
    en: "garlic",
    panix: "ya",
    sanjuan: "ya",
    yolo: "",
    yaite: "ya",
  },
  cebolla: {
    en: "onion",
    panix: "nsee",
    sanjuan: "nsee",
    yolo: "",
    yaite: "nse",
  },
  chile: {
    en: "chili",
    panix: "knyaf",
    sanjuan: "knyaf",
    yolo: "",
    yaite: "nia",
  },
  cilantro: {
    en: "coriander",
    panix: "skoo",
    sanjuan: "skoo",
    yolo: "",
    yaite: "sko",
  },
  coco: {
    en: "coconut",
    panix: "klo",
    sanjuan: "klo",
    yolo: "",
    yaite: "klu",
  },
  durazno: {
    en: "peach",
    panix: "nka",
    sanjuan: "nka",
    yolo: "",
    yaite: "ña",
  },
  guayaba: {
    en: "guava",
    panix: "kwa",
    sanjuan: "kwa",
    yolo: "",
    yaite: "kua",
  },
  jitomate: {
    en: "tomato",
    panix: "bshee",
    sanjuan: "bshee",
    yolo: "",
    yaite: "msh",
  },
  jicama: {
    en: "jicama",
    panix: "kanch",
    sanjuan: "kanch",
    yolo: "",
    yaite: "traduccion no disponible",
  },
  limon: {
    en: "lemon",
    panix: "kne",
    sanjuan: "kne",
    yolo: "",
    yaite: "kne",
  },
  mango: {
    en: "mango",
    panix: "kwaa",
    sanjuan: "kwaa",
    yolo: "",
    yaite: "kua",
  },
  manzana: {
    en: "apple",
    panix: "sha",
    sanjuan: "sha",
    yolo: "",
    yaite: "sha",
  },
  melón: {
    en: "melon",
    panix: "tsa",
    sanjuan: "tsa",
    yolo: "",
    yaite: "tsa",
  },
  naranja: {
    en: "orange",
    panix: "yea",
    sanjuan: "yea",
    yolo: "",
    yaite: "yea",
  },
  papaya: {
    en: "papaya",
    panix: "tsoa",
    sanjuan: "tsoa",
    yolo: "",
    yaite: "soa",
  },
  pepino: {
    en: "cucumber",
    panix: "nkwa",
    sanjuan: "nkwa",
    yolo: "",
    yaite: "nkwa",
  },
  pera: {
    en: "pear",
    panix: "kwaa",
    sanjuan: "kwaa",
    yolo: "",
    yaite: "kua",
  },
  piña: {
    en: "pineapple",
    panix: "shii",
    sanjuan: "shii",
    yolo: "",
    yaite: "shi",
  },
  platano: {
    en: "banana",
    panix: "jwae",
    sanjuan: "jwae",
    yolo: "",
    yaite: "ua",
  },
  rábano: {
    en: "radish",
    panix: "ni",
    sanjuan: "ni",
    yolo: "",
    yaite: "nie",
  },
  sandia: {
    en: "watermelon",
    panix: "shi",
    sanjuan: "shi",
    yolo: "",
    yaite: "shi",
  },
  tomate: {
    en: "tomato",
    panix: "bshee",
    sanjuan: "bshee",
    yolo: "",
    yaite: "msh",
  },
  tuna: {
    en: "cactus fruit",
    panix: "tsan",
    sanjuan: "tsan",
    yolo: "",
    yaite: "tsa",
  },
  zanahoria: {
    en: "carrot",
    panix: "tshni",
    sanjuan: "tshni",
    yolo: "",
    yaite: "tni",
  },
  bandeja: {
    en: "Tray",
    panix: "s’iu",
    sanjuan: "SyuE",
    yolo: "",
    yaite: "s’iu",
  },
  escoba: {
    en: "Broom",
    panix: "kua",
    sanjuan: "KwaA",
    yolo: "",
    yaite: "kua",
  },
  abanico: {
    en: "Fan",
    panix: "traducción no disponible",
    sanjuan: "Abanico",
    yolo: "",
    yaite: "",
  },
  comal: {
    en: "Comal",
    panix: "ñ’o",
    sanjuan: "NyanA",
    yolo: "",
    yaite: "ñ’o",
  },
  olla: {
    en: "Pot",
    panix: "ki’itu",
    sanjuan: "KtonqA",
    yolo: "",
    yaite: "ki’itu",
  },
  cazo: {
    en: "Saucepan",
    panix: "sho’oo tn’u",
    sanjuan: "SqanE",
    yolo: "",
    yaite: "sho’oo tn’u",
  },
  cuchara: {
    en: "Spoon",
    panix: "f’chara",
    sanjuan: "KchaHraC",
    yolo: "",
    yaite: "f’chara",
  },
  leña: {
    en: "Firewood",
    panix: "i’aa",
    sanjuan: "ykaA",
    yolo: "",
    yaite: "i’aa",
  },
  silla: {
    en: "Chair",
    panix: "kas’lia",
    sanjuan: "YkaA shlyaK",
    yolo: "",
    yaite: "kas’lia",
  },
  mesa: {
    en: "Table",
    panix: "m’sa",
    sanjuan: "SaE",
    yolo: "",
    yaite: "m’sa",
  },
  metate: {
    en: "Metate",
    panix: "uak,chi",
    sanjuan: "KchiA",
    yolo: "",
    yaite: "uak,chi",
  },
  plato: {
    en: "Plate",
    panix: "ki’naa",
    sanjuan: "KqnaE",
    yolo: "",
    yaite: "ki’naa",
  },
  molcajete: {
    en: "Molcajete",
    panix: "",
    sanjuan: "KqnaC nta knyanqF",
    yolo: "",
    yaite: "",
  },
  baúl: {
    en: "Trunk",
    panix: "",
    sanjuan: "JnyaqG",
    yolo: "",
    yaite: "",
  },
  balanza: {
    en: "Scale",
    panix: "ska’bia",
    sanjuan: "Tikwan qwi jyaqC",
    yolo: "",
    yaite: "ska’bia",
  },
  bolsa: {
    en: "Bag",
    panix: "tki’f jii",
    sanjuan: "JenF",
    yolo: "",
    yaite: "tki’f jii",
  },
  cama: {
    en: "Bed",
    panix: "lo io",
    sanjuan: "KyqnyaG",
    yolo: "",
    yaite: "lo io",
  },
  calzón: {
    en: "Underwear",
    panix: "s’ lii",
    sanjuan: "SlyiK tykuqC",
    yolo: "",
    yaite: "s’ lii",
  },
  camisa: {
    en: "Shirt",
    panix: "i’ko",
    sanjuan: "YkaqF",
    yolo: "",
    yaite: "i’ko",
  },
  canasta: {
    en: "Basket",
    panix: "skui’i",
    sanjuan: "ShwiH",
    yolo: "",
    yaite: "skui’i",
  },
  casa: {
    en: "House",
    panix: "nho’o",
    sanjuan: "QanA",
    yolo: "",
    yaite: "nho’o",
  },
  cazuela: {
    en: "Stew Pot",
    panix: "sho’o",
    sanjuan: "SaAlaE",
    yolo: "",
    yaite: "sho’o",
  },
  cepillo: {
    en: "Brush",
    panix: "",
    sanjuan: "Cepillo",
    yolo: "",
    yaite: "",
  },
  cobija: {
    en: "Blanket",
    panix: "tek’cho",
    sanjuan: "TichaK",
    yolo: "",
    yaite: "tek’cho",
  },
  cruz: {
    en: "Cross",
    panix: "f’sii",
    sanjuan: "SiK",
    yolo: "",
    yaite: "f’sii",
  },
  detergente: {
    en: "Detergent",
    panix: "f’ia",
    sanjuan: "YjyaA",
    yolo: "",
    yaite: "f’ia",
  },
  dinero: {
    en: "Money",
    panix: "ñ’ii",
    sanjuan: "JnyiB",
    yolo: "",
    yaite: "ñ’ii",
  },
  dulce: {
    en: "Candy",
    panix: "shii",
    sanjuan: "YuE shiC",
    yolo: "",
    yaite: "shii",
  },
  escopeta: {
    en: "Shotgun",
    panix: "tku’u",
    sanjuan: "KwaF",
    yolo: "",
    yaite: "tku’u",
  },
  flor: {
    en: "Flower",
    panix: "k’e",
    sanjuan: "KtonH",
    yolo: "",
    yaite: "k’e",
  },
  fuego: {
    en: "Fire",
    panix: "ki’i",
    sanjuan: "KeC",
    yolo: "",
    yaite: "ki’i",
  },
  fotografía: {
    en: "Photograph",
    panix: "lio’ kui",
    sanjuan: "KiqC",
    yolo: "",
    yaite: "lio’ kui",
  },
  gota: {
    en: "Drop",
    panix: "i’tia",
    sanjuan: "TikwenC",
    yolo: "",
    yaite: "i’tia",
  },
  hierba: {
    en: "Herb",
    panix: "i’jshi",
    sanjuan: "Tsuq tyiqaA",
    yolo: "",
    yaite: "i’jshi",
  },
  hoja: {
    en: "Leaf",
    panix: "ka’a",
    sanjuan: "KshinC",
    yolo: "",
    yaite: "ka’a",
  },
  iglesia: {
    en: "Church",
    panix: "l’a",
    sanjuan: "Nka",
    yolo: "",
    yaite: "l’a",
  },
  limosna: {
    en: "Alms",
    panix: "",
    sanjuan: "LaG",
    yolo: "",
    yaite: "",
  },
  llaga: {
    en: "Wound",
    panix: "m’shi",
    sanjuan: "LoA stanH",
    yolo: "",
    yaite: "m’shi",
  },
  machete: {
    en: "Machete",
    panix: "f’chi",
    sanjuan: "Llaga",
    yolo: "",
    yaite: "f’chi",
  },
  mecate: {
    en: "Rope",
    panix: "t’i",
    sanjuan: "Shti",
    yolo: "",
    yaite: "t’i",
  },
  mugre: {
    en: "Dirt",
    panix: "ku’u",
    sanjuan: "TiE",
    yolo: "",
    yaite: "ku’u",
  },
  ofrenda: {
    en: "Offering",
    panix: "",
    sanjuan: "KuH",
    yolo: "",
    yaite: "",
  },
  oro: {
    en: "Gold",
    panix: "",
    sanjuan: "QoroF",
    yolo: "",
    yaite: "",
  },
  palma: {
    en: "Palm",
    panix: "k’ña",
    sanjuan: "JnyianH",
    yolo: "",
    yaite: "k’ña",
  },
  palabra: {
    en: "Word",
    panix: "ch’a",
    sanjuan: "Cha dwiriC",
    yolo: "",
    yaite: "ch’a",
  },
  palo: {
    en: "Stick",
    panix: "k’a",
    sanjuan: "YkaA",
    yolo: "",
    yaite: "k’a",
  },
  planta: {
    en: "Plant",
    panix: "i’jshi",
    sanjuan: "YkaA jniH",
    yolo: "",
    yaite: "i’jshi",
  },
  plástico: {
    en: "Plastic",
    panix: "k’lia",
    sanjuan: "YlyaqA",
    yolo: "",
    yaite: "k’lia",
  },
  rama: {
    en: "Branch",
    panix: "s’to’ka",
    sanjuan: "Staq ykaA",
    yolo: "",
    yaite: "s’to’ka",
  },
  sed: {
    en: "Thirst",
    panix: "kl’ti",
    sanjuan: "Ndiriq",
    yolo: "",
    yaite: "kl’ti",
  },
  rosa: {
    en: "Rose",
    panix: "i’ka’ke",
    sanjuan: "KeC shlyiaA",
    yolo: "",
    yaite: "i’ka’ke",
  },
  semilla: {
    en: "Seed",
    panix: "s’iu",
    sanjuan: "SqyuC",
    yolo: "",
    yaite: "s’iu",
  },
  servilleta: {
    en: "Napkin",
    panix: "t’mle",
    sanjuan: "LeA",
    yolo: "",
    yaite: "t’mle",
  },
  sol: {
    en: "Sun",
    panix: "f’cha",
    sanjuan: "KchaG",
    yolo: "",
    yaite: "f’cha",
  },
  sombrero: {
    en: "Hat",
    panix: "m’sblu",
    sanjuan: "SaAluE",
    yolo: "",
    yaite: "m’sblu",
  },
  tinta: {
    en: "Ink",
    panix: "ty’o",
    sanjuan: "TyqanG",
    yolo: "",
    yaite: "ty’o",
  },
  coser: {
    en: "Sew",
    panix: "xkwan",
    sanjuan: "ShqkwaH",
    yolo: "xkwan",
    yaite: "s’ kuo",
  },
  cortar: {
    en: "Cut",
    panix: "si´yu",
    sanjuan: "ShqyuL",
    yolo: "si'yu",
    yaite: "s’iu",
  },
  cuidar: {
    en: "Take care of",
    panix: "ku´ni",
    sanjuan: "Ne kasuE",
    yolo: "ku’ni kuwenta",
    yaite: "ni’ kuita",
  },
  abanicar: {
    en: "Fan",
    panix: "kula",
    sanjuan: "SqwaG qenH jloH",
    yolo: "Kula kwi’ in",
    yaite: "s’cuaif’",
  },
  acostumbrar: {
    en: "Get used to",
    panix: "tya´an ti",
    sanjuan: "TqariC",
    yolo: "kia’ an ti '",
    yaite: "s’cua’tie",
  },
  acompañar: {
    en: "Accompany",
    panix: "tsaa...lo´o",
    sanjuan: "SqwaA sanB",
    yolo: "tsaa lo’ o",
    yaite: "traducción no disponible",
  },
  aconsejar: {
    en: "Advise",
    panix: "ta...kasiya",
    sanjuan: "Tareq noqtiaA",
    yolo: "xu ‘wa tiya",
    yaite: "in’sat",
  },
  acordar: {
    en: "Agree",
    panix: "ñi…cha´",
    sanjuan: "tqwiriH",
    yolo: "Kiñin cha '",
    yaite: "s’ati",
  },
  aclarar: {
    en: "Clarify",
    panix: "tyuwi",
    sanjuan: "KqsaA sqwe",
    yolo: "tyuwi",
    yaite: "i’sat",
  },
  acomodar: {
    en: "Arrange",
    panix: "kiji´in ka´an",
    sanjuan: "ShtyiaH sqweI",
    yolo: "xtya tsu’ ve",
    yaite: "s’kio’sue",
  },
  aceptar: {
    en: "Accept",
    panix: "xñi",
    sanjuan: "ShlyiaA",
    yolo: "xñi cha '",
    yaite: "traducción no disponible",
  },
  acabar: {
    en: "Finish",
    panix: "ku´ni...tyii",
    sanjuan: "Neqtyiri",
    yolo: "ku’ni tyii",
    yaite: "traducción no disponible",
  },
  acusar: {
    en: "Accuse",
    panix: "jñan...ki´ya",
    sanjuan: "TaA qyaA",
    yolo: "jñan ki'ya",
    yaite: "in’sa",
  },
  adelantar: {
    en: "Advance",
    panix: "tyukwa lyoo",
    sanjuan: "JilyioE",
    yolo: "tyukwa loo",
    yaite: "traducción no disponible",
  },
  adornar: {
    en: "Decorate",
    panix: "ku´ni tkan´",
    sanjuan: "NeH tiqka",
    yolo: "ku’ni tkan",
    yaite: "ni’s’e",
  },
  adorar: {
    en: "Adore",
    panix: "ku´ni tnun",
    sanjuan: "NeH jnoF",
    yolo: "ku’ ni tnun",
    yaite: "traducción no disponible",
  },
  aflojar: {
    en: "Loosen",
    panix: "xtii",
    sanjuan: "NeH anal",
    yolo: "Xti",
    yaite: "ni’oo",
  },
  agachar: {
    en: "Duck",
    panix: "xkii",
    sanjuan: "ShqkyinG",
    yolo: "xkii",
    yaite: "traducción no disponible",
  },
  agarrar: {
    en: "Grab",
    panix: "xñii",
    sanjuan: "ShnyiF",
    yolo: "xñi",
    yaite: "o’ya",
  },
  almacenar: {
    en: "Store",
    panix: "xñi ti´in",
    sanjuan: "NkwanH",
    yolo: "xñi ti ' in",
    yaite: "s’uisie",
  },
  almorzar: {
    en: "Have lunch",
    panix: "ku lomsaa",
    sanjuan: "KunG saH",
    yolo: "ku lomsaa",
    yaite: "ku’ilia",
  },
  alumbrar: {
    en: "Light up",
    panix: "tyu´wi xaa",
    sanjuan: "QuE shaA",
    yolo: "xu ‘wi xaa",
    yaite: "traducción no disponible",
  },
  amarrar: {
    en: "Tie",
    panix: "skan",
    sanjuan: "Skáqïn",
    yolo: "skan '",
    yaite: "traducción no disponible",
  },
   aparecer: {
    en: "Appear",
    panix: "kwu´u loo",
    sanjuan: "NdqoG tonH",
    yolo: "",
    yaite: "traducción no disponible",
  },
  apagar: {
    en: "Turn off",
    panix: "si´yu ku´",
    sanjuan: "SwiqE",
    yolo: "",
    yaite: "s’sui",
  },
  apostar: {
    en: "Bet",
    panix: "tsaa ska kanan",
    sanjuan: "Apostar",
    yolo: "",
    yaite: "traducción no disponible",
  },
  apretar: {
    en: "Press",
    panix: "ku´ni tsaa",
    sanjuan: "NeH saE",
    yolo: "",
    yaite: "traducción no disponible",
  },
  arreglar: {
    en: "Fix",
    panix: "jñi",
    sanjuan: "NeG shweC",
    yolo: "",
    yaite: "nis’ue",
  },
  arruinar: {
    en: "Ruin",
    panix: "ku´ni ñu…un",
    sanjuan: "QneG chinH ndqanG",
    yolo: "",
    yaite: "traducción no disponible",
  },
  asistir: {
    en: "Attend",
    panix: "tya´an",
    sanjuan: "SqanF",
    yolo: "",
    yaite: "yi’a",
  },
  ayudar: {
    en: "Help",
    panix: "taya´",
    sanjuan: "TayaqF",
    yolo: "",
    yaite: "do’ya",
  },
  bañar: {
    en: "Bathe",
    panix: "xta chku",
    sanjuan: "Kta tikeF",
    yolo: "",
    yaite: "ia’ku",
  },
  balancear: {
    en: "Balance",
    panix: "skwen biya´",
    sanjuan: "NeG swaB",
    yolo: "",
    yaite: "traducción no disponible",
  },
  batir: {
    en: "Beat",
    panix: "xla",
    sanjuan: "ShiaqG",
    yolo: "",
    yaite: "traducción no disponible",
  },
  borrar: {
    en: "Erase",
    panix: "xka, kuniin",
    sanjuan: "KqtiH",
    yolo: "",
    yaite: "s’ka",
  },
  brillar: {
    en: "Shine",
    panix: "tya´an xaa",
    sanjuan: "ShaH",
    yolo: "",
    yaite: "dui",
  },
  brincar: {
    en: "Jump",
    panix: "tyo´o kwan",
    sanjuan: "QuE kwanI",
    yolo: "",
    yaite: "o’kuo",
  },
  brotar: {
    en: "Sprout",
    panix: "katsu",
    sanjuan: "TkwaH",
    yolo: "",
    yaite: "traducción no disponible",
  },
  burlar: {
    en: "Mock",
    panix: "liye´ ti",
    sanjuan: "Dyieriq",
    yolo: "",
    yaite: "lie’ti",
  },
  buscar: {
    en: "Search",
    panix: "kunaan",
    sanjuan: "KyaAnaF",
    yolo: "",
    yaite: "kia’no",
  },
  calcular: {
    en: "Calculate",
    panix: "kulo biya´",
    sanjuan: "LoG jiaqA",
    yolo: "",
    yaite: "traducción no disponible",
  },
  cambiar: {
    en: "Change",
    panix: "xa´an",
    sanjuan: "ShqanA",
    yolo: "",
    yaite: "s’oo",
  },
  cargar: {
    en: "Carry",
    panix: "kwi´ya",
    sanjuan: "LaL",
    yolo: "",
    yaite: "m’ia",
  },
  cobrar: {
    en: "Charge",
    panix: "kwi´ya",
    sanjuan: "ShniliyaI",
    yolo: "",
    yaite: "traducción no disponible",
  },
  conducir: {
    en: "Drive",
    panix: "su´wa ta",
    sanjuan: "Tqyia qo carroC",
    yolo: "",
    yaite: "l’ia",
  },
  confesar: {
    en: "Confess",
    panix: "kunee",
    sanjuan: "KsaqE chaq",
    yolo: "",
    yaite: "traducción no disponible",
  },
  confirmar: {
    en: "Confirm",
    panix: "ta biya",
    sanjuan: "KsaqE chaq sqweraH",
    yolo: "",
    yaite: "traducción no disponible",
  },
  conformar: {
    en: "Conform",
    panix: "takiya",
    sanjuan: "Sqwe jiaqA",
    yolo: "",
    yaite: "traducción no disponible",
  },
  confundir: {
    en: "Confuse",
    panix: "xtyaa",
    sanjuan: "NeH tuK",
    yolo: "",
    yaite: "traducción no disponible",
  },
  congelar: {
    en: "Freeze",
    panix: "kala",
    sanjuan: "NeH keC",
    yolo: "",
    yaite: "traducción no disponible",
  },
  conocer: {
    en: "Know",
    panix: "jlyo ti",
    sanjuan: "TqwilyioF",
    yolo: "",
    yaite: "traducción no disponible",
  },
  contar: {
    en: "Count",
    panix: "kwa",
    sanjuan: "Ktsaq",
    yolo: "",
    yaite: "ku’o",
  },
  contestar: {
    en: "Answer",
    panix: "xkwen",
    sanjuan: "ShkwenH",
    yolo: "",
    yaite: "s’kue",
  },
  controlar: {
    en: "Control",
    panix: "kwa´a",
    sanjuan: "Kwa qa",
    yolo: "",
    yaite: "traducción no disponible",
  },
  cosechar: {
    en: "Harvest",
    panix: "ku´nan",
    sanjuan: "KtaA",
    yolo: "",
    yaite: "traducción no disponible",
  },
  costar: {
    en: "Cost",
    panix: "nsu´wi liya´ lo",
    sanjuan: "NdqanG",
    yolo: "",
    yaite: "traducción no disponible",
  },
  amarillo_de_pollo: {
    en: "chicken broth / yolk",
    panix: "tyooa skwang kwtug",
    sanjuan: "TyjqaA skwanA ktuH",
    yolo: "yee kwitu",
    yaite: "skua ftu",
  },
  calabaza: {
    en: "pumpkin",
    panix: "tyjo",
    sanjuan: "YjoH",
    yolo: "kyojo",
    yaite: "jio",
  },
  caldo_de_camaron: {
    en: "shrimp broth",
    panix: "kluc toag",
    sanjuan: "KluH ktaG",
    yolo: "kalu tita",
    yaite: "kla taa",
  },
  caldo_de_chacal: {
    en: "chacal broth",
    panix: "kluc tnug",
    sanjuan: "KluH tnoH",
    yolo: "kalu tinu",
    yaite: "kla taa",
  },
  caldo_de_chepil: {
    en: "chepil broth",
    panix: "kluc taa ykoaa",
    sanjuan: "KluH ktah YkaA",
    yolo: "kitaa",
    yaite: "ka kta",
  },
  caldo_de_ejote: {
    en: "green bean broth",
    panix: "kluc ndoaa kunee",
    sanjuan: "KluH ndaA jneqE",
    yolo: "kalu ndaa kwine´",
    yaite: "kla dafine",
  },
  caldo_de_nopal: {
    en: "cactus broth",
    panix: "kluc yoaf",
    sanjuan: "KluH yaF",
    yolo: "kalu yaa",
    yaite: "kla ja",
  },
  caldo_de_platano_verde: {
    en: "green plantain broth",
    panix: "kluc juwae",
    sanjuan: "KluH qwaB nqgaG",
    yolo: "Kalu ju’wa ya’a",
    yaite: "kla ua",
  },
  caldo_rabo_iguana_verde: {
    en: "iguana tail stew",
    panix: "kluc taa kwtsef",
    sanjuan: "KluH",
    yolo: "Kalu kutsi",
    yaite: "traducción no disponible",
  },
  chicatana: {
    en: "ant mole",
    panix: "kena ntseine",
    sanjuan: "KetsenH",
    yolo: "Kïsï",
    yaite: "kensii",
  },
  frijoles: {
    en: "beans",
    panix: "ndoa",
    sanjuan: "NdahH",
    yolo: "ndaa",
    yaite: "nda",
  },
  memela_rabo_iguana: {
    en: "iguana tail memela",
    panix: "kluc taa kwtsef",
    sanjuan: "YjakuqG",
    yolo: "Milaa kee tii",
    yaite: "skua ftshi",
  },
  memelas_flor_calabaza: {
    en: "squash flower memelas",
    panix: "fleag taa tic",
    sanjuan: "YjakuqG keH yjoH",
    yolo: "",
    yaite: "jaku ti",
  },
  memelitas_frijol: {
    en: "bean memelitas",
    panix: "jakoa ndaan",
    sanjuan: "YjakuqG ndaH",
    yolo: "",
    yaite: "jaku",
  },
  mole_hierba_pescado: {
    en: "fish herb mole",
    panix: "tyooaa skwang ndaa kwloac",
    sanjuan: "MoleH",
    yolo: "",
    yaite: "skua kda flat",
  },
  nopales: {
    en: "prickly pear cactus",
    panix: "yoaf",
    sanjuan: "YaF",
    yolo: "",
    yaite: "ya",
  },
  pan: {
    en: "bread",
    panix: "jaxlya",
    sanjuan: "JashlaB",
    yolo: "",
    yaite: "traducción no disponible",
  },
  picaditas: {
    en: "small fried tortillas",
    panix: "fleag ktue",
    sanjuan: "Picaditas",
    yolo: "",
    yaite: "traducción no disponible",
  },
  pie_de_gallo: {
    en: "rooster’s foot",
    panix: "ktoaf ti yoac",
    sanjuan: "KtaH kqiaG",
    yolo: "",
    yaite: "kia lofe",
  },
  queso: {
    en: "cheese",
    panix: "kshuc",
    sanjuan: "KshuH",
    yolo: "",
    yaite: "kshu",
  },
  salsa_chicatana: {
    en: "ant salsa",
    panix: "tyooaa knyaf kenc ntseine",
    sanjuan: "TyjqaH knyiaqG ketsenH",
    yolo: "",
    yaite: "ia kensii",
  },
  salsa_semilla_calabaza: {
    en: "pumpkin seed salsa",
    panix: "tyooaa knyaf siyuc tyjog",
    sanjuan: "Tyjqa knyiaqG sqiuG yjoH",
    yolo: "",
    yaite: "ia daijo",
  },
  salsa_tomate: {
    en: "tomato salsa",
    panix: "tyooaa knyaf bshee",
    sanjuan: "Tyjqa knyiaqG shiH",
    yolo: "",
    yaite: "kla msh",
  },
  tamal_de_rana: {
    en: "frog tamale",
    panix: "jaa ktoni kwtyi",
    sanjuan: "JaktonqG ktiqG",
    yolo: "",
    yaite: "ijatuufthi",
  },
  tortilla_maiz_nuevo: {
    en: "fresh corn tortilla",
    panix: "tyjoaa nskwac kunei",
    sanjuan: "YjaH skwaqG kwiH",
    yolo: "",
    yaite: "ija",
  },
  tostada: {
    en: "toasted tortilla",
    panix: "tyjoaa biia",
    sanjuan: "YjaH kqiG",
    yolo: "",
    yaite: "ija mi",
  },
  tostada_corozo: {
    en: "corozo toast",
    panix: "tyjoaa mbloi",
    sanjuan: "YjaH shiH",
    yolo: "",
    yaite: "ijamä",
  },
  uno: {
  en: "One",
  sanjuan: "skaᴬ",
  panix: "Skoa",
  yolo: "",
  yaite: "ska",
  },

  dos: {
    en: "Two",
    sanjuan: "tkwaJ",
    panix: "Tkwoa",
    yolo: "",
    yaite: "t’wua",
  },

  tres: {
    en: "Three",
    sanjuan: "snaJ",
    panix: "Snan",
    yolo: "",
    yaite: "s’na",
  },

  cuatro: {
    en: "Four",
    sanjuan: "jaᴬ kwaᴬ",
    panix: "Jakwoa",
    yolo: "",
    yaite: "ja’kua",
  },

  cinco: {
    en: "Five",
    sanjuan: "qyuᴬ",
    panix: "Ki'yu",
    yolo: "",
    yaite: "ka’iu",
  },

  seis: {
    en: "Six",
    sanjuan: "skwaJ",
    panix: "Skwoa",
    yolo: "",
    yaite: "s’cua",
  },

  siete: {
    en: "Seven",
    sanjuan: "ktiJ",
    panix: "Kti",
    yolo: "",
    yaite: "ka’tii",
  },

  ocho: {
    en: "Eight",
    sanjuan: "snoqᴬ",
    panix: "Sno",
    yolo: "",
    yaite: "s’nuu",
  },

  nueve: {
    en: "Nine",
    sanjuan: "kaJ",
    panix: "Koa",
    yolo: "",
    yaite: "k’aa",
  },

  diez: {
    en: "Ten",
    sanjuan: "tiJ",
    panix: "Ti",
    yolo: "",
    yaite: "t’i",
  },

  once: {
    en: "Eleven",
    sanjuan: "tiJ shkal",
    panix: "Ti shkoa",
    yolo: "",
    yaite: "tis’ḱa",
  },

  doce: {
    en: "Twelve",
    sanjuan: "tiJ tykwaᴴ",
    panix: "Ti tykwoa",
    yolo: "",
    yaite: "tis’kua",
  },

  trece: {
    en: "Thirteen",
    sanjuan: "tiJ shnaH",
    panix: "Ti shnan",
    yolo: "",
    yaite: "tís’noo",
  },

  catorce: {
    en: "Fourteen",
    sanjuan: "tiJ ykwa",
    panix: "Ti lykwoa",
    yolo: "",
    yaite: "tiḱua",
  },

  quince: {
    en: "Fifteen",
    sanjuan: "qnyoJ",
    panix: "Ti yon",
    yolo: "",
    yaite: "nyo",
  },

  dieciseis: {
    en: "Sixteen",
    sanjuan: "qnyoJ shkal",
    panix: "Ti'yon shkoa",
    yolo: "",
    yaite: "nyo’shka",
  },

  diecisiete: {
    en: "Seventeen",
    sanjuan: "qnyoJ tykwaH",
    panix: "Ti'yon tykwoa",
    yolo: "",
    yaite: "nyo’ tkua",
  },

  dieciocho: {
    en: "Eighteen",
    sanjuan: "qnyoJ shnaH",
    panix: "Ti'yon shnan",
    yolo: "",
    yaite: "nyo’sna",
  },

  diecinueve: {
    en: "Nineteen",
    sanjuan: "qnyoJ ykwaᴵ",
    panix: "Ti'yon lykwoa",
    yolo: "",
    yaite: "nyo’jkan",
  },

  veinte: {
    en: "Twenty",
    sanjuan: "klaJ",
    panix: "Kla",
    yolo: "",
    yaite: "kla",
  },

  veintiuno: {
    en: "Twenty-One",
    sanjuan: "klaJ ndwaK skaH",
    panix: "Kla ndo skoa",
    yolo: "",
    yaite: "kla’ndua’ska",
  },

  veintidos: {
    en: "Twenty-Two",
    sanjuan: "klaJ ndwaK tkwaH",
    panix: "Kla ndo Tkwoa",
    yolo: "",
    yaite: "kla’ndua’tkua",
  },

  veintitres: {
    en: "Twenty-Three",
    sanjuan: "klaJ ndwaK snaH",
    panix: "Kla ndo Snan",
    yolo: "",
    yaite: "kla’ndua’sna",
  },

  veinticuatro: {
    en: "Twenty-Four",
    sanjuan: "klaJ ndwaK jaK kwaJ",
    panix: "Kla ndo Jakwoa",
    yolo: "",
    yaite: "kla’ndua’jakua",
  },

  veinticinco: {
    en: "Twenty-Five",
    sanjuan: "klaJ qyuK",
    panix: "Kla ngi'yu",
    yolo: "",
    yaite: "kla’yu",
  },

  veintiseis: {
    en: "Twenty-Six",
    sanjuan: "klaJ ndwaK skwaH",
    panix: "Kla ndo Skwoa",
    yolo: "",
    yaite: "kla’ndua’skua",
  },

  veintisiete: {
    en: "Twenty-Seven",
    sanjuan: "klaJ ndwaK ktiH",
    panix: "Kla ndo Kti",
    yolo: "",
    yaite: "kla’ndua’kti",
  },

  veintiocho: {
    en: "Twenty-Eight",
    sanjuan: "klaJ ndwak snoqh",
    panix: "Kla ndo Sno'",
    yolo: "",
    yaite: "kla’ndua’sno",
  },

  veintinueve: {
    en: "Twenty-Nine",
    sanjuan: "klaJ ndwaK kaH",
    panix: "Kla ndo ko",
    yolo: "",
    yaite: "kla’ndua’ka",
  },

  treinta: {
    en: "Thirty",
    sanjuan: "klaJ tyiH",
    panix: "Kla Tyi",
    yolo: "",
    yaite: "kla’tyi",
  },

  treinta_y_uno: {
    en: "Thirty-One",
    sanjuan: "klaJ tyiH ndwaᴮ skaK",
    panix: "Kla tyi ndo skoa",
    yolo: "",
    yaite: "kla’tyindua’ska",
  },

  treinta_y_dos: {
    en: "Thirty-Two",
    sanjuan: "klaJ tyiH ndwaB tkwaH",
    panix: "Kla tyi ndo Tkwoa",
    yolo: "",
    yaite: "kla’tyi’ndua’tkua",
  },

  treinta_y_tres: {
    en: "Thirty-Three",
    sanjuan: "klaJ tyiH ndwaᴮ snaH",
    panix: "Kla tyi ndo Snan",
    yolo: "",
    yaite: "la’tyi’ndua’sna",
  },

  treinta_y_cuatro: {
    en: "Thirty-Four",
    sanjuan: "klaJ tyiH ndwaᴮ jaK kwa",
    panix: "Kla tyi ndo Jakwoa",
    yolo: "",
    yaite: "kla’tyi’ndua’jakua",
  },
  treinta_y_cinco: {
  en: "Thirty-Five",
  sanjuan: "klaJ qnyoK",
  panix: "Kla ndi'yon",
  yolo: "",
  yaite: "kla’ nyo",
  },

  treinta_y_seis: {
    en: "Thirty-Six",
    sanjuan: "klaJ tyiH ndwaᴮ skwaH",
    panix: "Kla tyi ndo Skwoa",
    yolo: "",
    yaite: "kla’tyi’ndua’skua",
  },

  treinta_y_siete: {
    en: "Thirty-Seven",
    sanjuan: "klaJ tyiH ndwaᴮ ktiH",
    panix: "Kla tyi ndo Kti",
    yolo: "",
    yaite: "kla’tyi’ndua’kti",
  },

  treinta_y_ocho: {
    en: "Thirty-Eight",
    sanjuan: "klaJ tyiH ndwaᴮ snoqH",
    panix: "Kla tyi ndo sno'",
    yolo: "",
    yaite: "kla’tyi’ndua’sno",
  },

  treinta_y_nueve: {
    en: "Thirty-Nine",
    sanjuan: "klaJ tyiH ndwaᴮ kaH",
    panix: "Kla tyi ndo koa",
    yolo: "",
    yaite: "kla’tyi’ndua’ka",
  },

  cuarenta: {
    en: "Forty",
    sanjuan: "tqwaJ",
    panix: "Tu'woa",
    yolo: "",
    yaite: "t’ua",
  },

  cuarenta_y_uno: {
    en: "Forty-One",
    sanjuan: "tqwaJ ndwaK skaK",
    panix: "Tu'woa ndo skoa",
    yolo: "",
    yaite: "t’ua’ndua’ska",
  },

  cuarenta_y_dos: {
    en: "Forty-Two",
    sanjuan: "tqwaJ ndwaK tkwaH",
    panix: "Tu'woa ndo Tkwoa",
    yolo: "",
    yaite: "t’ua’ndua’tkua",
  },

  cuarenta_y_tres: {
    en: "Forty-Three",
    sanjuan: "tqwaJ ndwaK snaH",
    panix: "Tu'woa ndo Snan",
    yolo: "",
    yaite: "t’ua’ndua’sna",
  },

  cuarenta_y_cuatro: {
    en: "Forty-Four",
    sanjuan: "tqwaJ ndwaK jaKkwaJ",
    panix: "Tu'woa ndo Jakwoa",
    yolo: "",
    yaite: "t’ua’ndua’jakua",
  },

  cuarenta_y_cinco: {
    en: "Forty-Five",
    sanjuan: "tqwaJ qyuJ",
    panix: "Tu'woa ngi'yo",
    yolo: "",
    yaite: "t’ua’ nyo",
  },

  cuarenta_y_seis: {
    en: "Forty-Six",
    sanjuan: "tqwaJ ndwa skwaH",
    panix: "Tu'woa ndo Skwoa",
    yolo: "",
    yaite: "t’ua’ndua’skua",
  },

  cuarenta_y_siete: {
    en: "Forty-Seven",
    sanjuan: "tqwaJ ndwaK ktiH",
    panix: "Tu'woa ndo Kti",
    yolo: "",
    yaite: "t’ua’ndua’kti",
  },

  cuarenta_y_ocho: {
    en: "Forty-Eight",
    sanjuan: "tqwaJ ndwaK snoqH",
    panix: "Tu'woa ndo sno'",
    yolo: "",
    yaite: "t’ua’ndua’sno",
  },

  cuarenta_y_nueve: {
    en: "Forty-Nine",
    sanjuan: "tqwaJ ndwaK kaH",
    panix: "Tu'woa ndo koa",
    yolo: "",
    yaite: "t’ua’ndua’ka",
  },

  cincuenta: {
    en: "Fifty",
    sanjuan: "tqwaJ tyiH",
    panix: "Tu'woa Tyi",
    yolo: "",
    yaite: "t’ua’ tyi",
  },

  cincuenta_y_uno: {
    en: "Fifty-One",
    sanjuan: "tqwaJ tyiH ndwaB skaK",
    panix: "Tu'woa tyi ndo skoa",
    yolo: "",
    yaite: "t’ua’tyi’ndua’ska",
  },

  cincuenta_y_dos: {
    en: "Fifty-Two",
    sanjuan: "tqwaJ tyiH ndwaB tkwaH",
    panix: "Tu'woa tyi ndo Tkwoa",
    yolo: "",
    yaite: "t’ua’tyi’ndua’tkua",
  },

  cincuenta_y_tres: {
    en: "Fifty-Three",
    sanjuan: "tqwaJ tyiH ndwaB snaH",
    panix: "Tu'woa tyi ndo Snan",
    yolo: "",
    yaite: "t’ua’tyi’ndua’sna",
  },

  cincuenta_y_cuatro: {
    en: "Fifty-Four",
    sanjuan: "tqwaJ tyiH ndwaB jaKkwaJ",
    panix: "Tu'woa tyi ndo Jakwoa",
    yolo: "",
    yaite: "t’ua’tyi’ndua’jakua",
  },

  cincuenta_y_cinco: {
    en: "Fifty-Five",
    sanjuan: "tqwaJ qnyoJ",
    panix: "Tu'woa ndi'yon",
    yolo: "",
    yaite: "t’ua’ nyo",
  },

  cincuenta_y_seis: {
    en: "Fifty-Six",
    sanjuan: "tqwaJ tyiH ndwaB skwaH",
    panix: "Tu'woa tyi ndo Skwoa",
    yolo: "",
    yaite: "t’ua’tyi’ndua’skua",
  },

  cincuenta_y_siete: {
    en: "Fifty-Seven",
    sanjuan: "tqwaJ tyiH ndwaB ktiH",
    panix: "Tu'woa tyi ndo Kti",
    yolo: "",
    yaite: "t’ua’tyi’ndua’kti",
  },

  cincuenta_y_ocho: {
    en: "Fifty-Eight",
    sanjuan: "tqwaJ tyiH ndwaB snoqH",
    panix: "Tu'woa tyi ndo Sno'",
    yolo: "",
    yaite: "t’ua’tyi’ndua’sno",
  },

  cincuenta_y_nueve: {
    en: "Fifty-Nine",
    sanjuan: "tqwaJ tyiH ndwaB kaH",
    panix: "Tu'woa tyi ndo Koa",
    yolo: "",
    yaite: "t’ua’tyi’ndua’ka",
  },

  sesenta: {
    en: "Sixty",
    sanjuan: "SnaJ ylaC",
    panix: "Snan yloa",
    yolo: "",
    yaite: "sna’ yla",
  },

  sesenta_y_uno: {
    en: "Sixty-One",
    sanjuan: "SnaJ ylaC ndwaB skaK",
    panix: "Snan yloa ntsu'wi Skoa",
    yolo: "",
    yaite: "sna’ yla’ ndua’ ska",
  },

  sesenta_y_dos: {
    en: "Sixty-Two",
    sanjuan: "SnaJ ylaC ndwaB tkwaH",
    panix: "Snan yloa ntsu'wi Tkwoa",
    yolo: "",
    yaite: "sna’ yla’ ndua’ tkua",
  },

  sesenta_y_tres: {
    en: "Sixty-Three",
    sanjuan: "SnaJ ylaC ndwaB snaH",
    panix: "Snan yloa ntsu'wi Snan",
    yolo: "",
    yaite: "sna’ yla’ ndua’ sna",
  },

  sesenta_y_cuatro: {
    en: "Sixty-Four",
    sanjuan: "SnaJ ylaC ndwaB jaKkwaJ",
    panix: "Snan yloa ntsu'wi Jakwoa",
    yolo: "",
    yaite: "sna’ yla’ ndua’ jakua",
  },

  sesenta_y_cinco: {
    en: "Sixty-Five",
    sanjuan: "SnaJ ylaC qwi7 qyuE",
    panix: "Snan yloa ntsu'wi Ki'yu",
    yolo: "",
    yaite: "sna’ yla’ ndua’",
  },

  sesenta_y_seis: {
    en: "Sixty-Six",
    sanjuan: "SnaJ ylaC qwiE skwaH",
    panix: "Snan yloa ntsu'wi Skwoa",
    yolo: "",
    yaite: "sna’ yla’ ndua’ skua",
  },

  sesenta_y_siete: {
    en: "Sixty-Seven",
    sanjuan: "SnaJ ylaC qwiE ktiE",
    panix: "Snan yloa ntsu'wi Kti",
    yolo: "",
    yaite: "sna’ yla’ ndua’ kti",
  },

  sesenta_y_ocho: {
    en: "Sixty-Eight",
    sanjuan: "SnaJ ylaC qwiE snoqE",
    panix: "Snan yloa ntsu'wi sno'",
    yolo: "",
    yaite: "sna’ yla’ ndua’ sno",
  },

  sesenta_y_nueve: {
    en: "Sixty-Nine",
    sanjuan: "SnaJ ylaC qwiE kaE",
    panix: "Snan yloa ntsu'wi koa",
    yolo: "",
    yaite: "sna’ yla’ ndua’ ka",
  },

  setenta: {
    en: "Seventy",
    sanjuan: "SnaJ ylaC qwiE tiE",
    panix: "Snan yloa ntsu'wi Ti",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui",
  },

  setenta_y_uno: {
    en: "Seventy-One",
    sanjuan: "SnaJ ylaC qwiE tiE shkaI",
    panix: "Snan yloa ntsu'wi Ti shkoa",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui’ ska",
  },

  setenta_y_dos: {
    en: "Seventy-Two",
    sanjuan: "SnaJ ylaC qwiE tiJ tykwaH",
    panix: "Snan yloa ntsu'wi Ti Tykwoa",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui tkua",
  },

  setenta_y_tres: {
    en: "Seventy-Three",
    sanjuan: "SnaJ ylaC qwiE tiJ shnaE",
    panix: "Snan yloa ntsu'wi Ti shnan",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui’ ti’sna",
  },

  setenta_y_cuatro: {
    en: "Seventy-Four",
    sanjuan: "SnaJ ylaC qwiE tiJ ykwaI",
    panix: "Snan yloa ntsu'wi Ti lykwoa",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui ti’ykua",
  },

  setenta_y_cinco: {
    en: "Seventy-Five",
    sanjuan: "SnaJ ylaC qwiE qnyoE",
    panix: "Snan yloa ntsu'wi Ti'yon",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui’ nyo",
  },

  setenta_y_seis: {
    en: "Seventy-Six",
    sanjuan: "SnaJ ylaC qwiE qnyoJ shkaI",
    panix: "Snan yloa ntsu'wi Ti'yon shkoa",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui nyo’ shka",
  },

  setenta_y_siete: {
    en: "Seventy-Seven",
    sanjuan: "SnaJ ylaC qwiE qnyoJ tykwaH",
    panix: "Snan yloa ntsu'wi Ti'yon Tykwoa",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui nyo’ tkua",
  },

  setenta_y_ocho: {
    en: "Seventy-Eight",
    sanjuan: "SnaJ ylaC qwiE qnyoJ shnaH",
    panix: "Snan yloa ntsu'wi Ti'yon Shnan",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui’ nyo’ shna",
  },

  setenta_y_nueve: {
    en: "Seventy-Nine",
    sanjuan: "SnaJ ylaC qwiE qnyoJ ykwaI",
    panix: "Snan yloa ntsu'wi Ti'yon lykwoa",
    yolo: "",
    yaite: "sna’ yla’ nsu’ui’ nyo’ jkua",
  },

  ochenta: {
    en: "Eighty",
    sanjuan: "JaA kwaA ylaC",
    panix: "Jakwoa yloa",
    yolo: "",
    yaite: "jakua’ yla",
  },

  ochenta_y_uno: {
    en: "Eighty-One",
    sanjuan: "JaA kwaA ylaC qwiE skaE",
    panix: "Jakwoa yloa ntsu'wi skoa",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ ska",
  },

  ochenta_y_dos: {
    en: "Eighty-Two",
    sanjuan: "JaA kwaA ylaC qwiE tkwaE",
    panix: "Jakwoa yloa ntsu'wi Tkwoa",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ tkua",
  },

  ochenta_y_tres: {
    en: "Eighty-Three",
    sanjuan: "JaA kwaA ylaC qwiE snaE",
    panix: "Jakwoa yloa ntsu'wi Snan",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ sna",
  },

  ochenta_y_cuatro: {
    en: "Eighty-Four",
    sanjuan: "JaA kwaA ylaC qwiE jaE kwaJ",
    panix: "Jakwoa yloa ntsu'wi Jakwoa",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ jakua",
  },

  ochenta_y_cinco: {
    en: "Eighty-Five",
    sanjuan: "JaA kwaA ylaC qwiE qyuE",
    panix: "Jakwoa yloa ntsu'wi Ki'yu",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui’ yu",
  },

  ochenta_y_seis: {
    en: "Eighty-Six",
    sanjuan: "JaA kwaA ylaC qwiE skwaE",
    panix: "Jakwoa yloa ntsu'wi Skwoa",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ skua",
  },

  ochenta_y_siete: {
    en: "Eighty-Seven",
    sanjuan: "JaA kwaA ylaC qwiE ktiE",
    panix: "Jakwoa yloa ntsu'wi Kti",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ kti",
  },

  ochenta_y_ocho: {
    en: "Eighty-Eight",
    sanjuan: "JaA kwaA ylaC qwiE snoqE",
    panix: "Jakwoa yloa ntsu'wi Sno",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ sno",
  },

  ochenta_y_nueve: {
    en: "Eighty-Nine",
    sanjuan: "JaA kwaA ylaC qwiE kaE",
    panix: "Jakwoa yloa ntsu'wi koa",
    yolo: "",
    yaite: "jakua’ yla’ ndua’ ka",
  },

  noventa: {
    en: "Ninety",
    sanjuan: "JaA kwaA ylaC qwiE tiE",
    panix: "Jakwoa yloa ntsu'wi Ti",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti",
  },

  noventa_y_uno: {
    en: "Ninety-One",
    sanjuan: "JaA kwaA ylaC qwiE tiJ shkaI",
    panix: "Jakwoa yloa ntsu'wi Ti shkoa",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ ska",
  },

  noventa_y_dos: {
    en: "Ninety-Two",
    sanjuan: "JaA kwaA ylaC qwiE tiJ tykwaH",
    panix: "Jakwoa yloa ntsu'wi Ti tykwoa",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ tkua",
  },

  noventa_y_tres: {
    en: "Ninety-Three",
    sanjuan: "JaA kwaA ylaC qwiE tiJ shnaH",
    panix: "Jakwoa yloa ntsu'wi Ti shnan",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ sna",
  },

  noventa_y_cuatro: {
    en: "Ninety-Four",
    sanjuan: "JaA kwaA ylaC qwiE tiJ ykwaI",
    panix: "Jakwoa yloa ntsu'wi Ti lykwoa",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ jakua",
  },

  noventa_y_cinco: {
    en: "Ninety-Five",
    sanjuan: "JaA kwaA ylaC qwiE qnyoJ",
    panix: "Jakwoa yloa ntsu'wi Ti'yon",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ nyo",
  },

  noventa_y_seis: {
    en: "Ninety-Six",
    sanjuan: "JaA kwaA ylaC qwiE qnyoJ shkaI",
    panix: "Jakwoa yloa ntsu'wi Ti'yon Shkoa",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ nyo’ ska",
  },

  noventa_y_siete: {
    en: "Ninety-Seven",
    sanjuan: "JaA kwaA ylaC qwiE qnyoJ tykwaI",
    panix: "Jakwoa yloa ntsu'wi Ti'yon tykwoa",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ nyo’ tkua",
  },

  noventa_y_ocho: {
    en: "Ninety-Eight",
    sanjuan: "JaA kwaA ylaC qwiE qnyoJ shnaH",
    panix: "Jakwoa yloa ntsu'wi Ti'yon Shnan",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ nyo’ sna",
  },

  noventa_y_nueve: {
    en: "Ninety-Nine",
    sanjuan: "JaA kwaA ylaC qwiE qnyoJ ykwaI",
    panix: "Jakwoa yloa ntsu'wi Ti'yon Lykwoa",
    yolo: "",
    yaite: "jakua’ yla’ nsu’ui ti’ nyo’ jakua",
  },

  cien: {
    en: "One Hundred",
    sanjuan: "SkaA sentuK",
    panix: "Skoa sintu",
    yolo: "",
    yaite: "ska’ sentu’",
  }, 
};


document.addEventListener("DOMContentLoaded", () => {
  const boton = document.getElementById("traducir");
  const texto = document.getElementById("texto");
  const idioma = document.getElementById("idioma");
  const resultado = document.getElementById("resultado");

  boton.addEventListener("click", () => {
    const palabra = texto.value.toLowerCase().trim();
    const idiomaSeleccionado = idioma.value;

    if (traducciones[palabra] && traducciones[palabra][idiomaSeleccionado]) {
      resultado.value = traducciones[palabra][idiomaSeleccionado];
    } else {
      resultado.value = "No se encontró la traducción 😔";
    }
  });
});


function pegarTexto() {
  navigator.clipboard.readText()
    .then(texto => {
      document.getElementById("texto").value = texto;
    })
    .catch(err => {
      console.log("Error al pegar:", err);
      alert("No se pudo acceder al portapapeles.");
    });
}


function compartirApp() {
  if (navigator.share) {
    navigator.share({
      title: 'Triccionario',
      text: 'Checa esta app para traducir palabras',
      url: window.location.href
    })
    .catch((error) => console.log('Error al compartir', error));
  } else {
    alert("Tu dispositivo no soporta la opción de compartir.");
  }
}


document.addEventListener("DOMContentLoaded", () => {
  const menuIcono = document.getElementById("menuIcono");
  const menuDesplegable = document.getElementById("menuDesplegable");

  // Abrir/cerrar menú al tocar el ícono
  menuIcono.addEventListener("click", (event) => {
    event.stopPropagation(); // evita cierre inmediato
    menuDesplegable.style.display =
      menuDesplegable.style.display === "block" ? "none" : "block";
  });

  // Cerrar menú al tocar fuera
  document.addEventListener("click", (event) => {
    if (!menuDesplegable.contains(event.target)) {
      menuDesplegable.style.display = "none";
    }
  });
});


function mostrarSeccion(id) {
  document.querySelectorAll('.seccion').forEach(sec => {
    sec.classList.remove('visible');
  });

  // Mostrar la sección seleccionada
  document.getElementById(id).classList.add('visible');

  // Cerrar menú después de seleccionar
  document.getElementById("menuDesplegable").style.display = "none";
}